# Generated by Django 5.1.2 on 2024-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingitems', '0002_alter_shoppingcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
