# Generated by Django 5.1.2 on 2024-10-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingitems', '0003_shoppingcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Womendress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_model_type', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingitems.shoppingcategory')),
            ],
        ),
    ]
