# Generated by Django 5.1.2 on 2024-10-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingitems', '0005_boysdress_kidsdress'),
    ]

    operations = [
        migrations.AddField(
            model_name='womendress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='womensubcategory/'),
        ),
    ]
