# Generated by Django 5.1.2 on 2024-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, 'Customer'), (2, 'Business'), (2, 'Admin')], null=True),
        ),
    ]
