# Generated by Django 5.1.2 on 2024-10-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingitems', '0005_boysdress_kidsdress'),
        ('women', '0002_womendreses_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='womenDreses',
            new_name='WomenDresesItems',
        ),
    ]
